### ISSUE TITLE
Keyboard Shortcut Support? 

### ISSUE THREAD

**Issue by sachinsid** [trophygeek/universalvideomaximizer#8]
**Is your feature request related to a problem? Please describe.**
None specifically

**Describe the solution you'd like**
Ability to map a keyboard shortcut to automatically invoke maximise/zoom mode on a tab

**Describe alternatives you've considered**
None

**Additional context**
Having this feature could improve overall user experience for users with keyboard workflows

Thank you for this extension!

**Comment by trophygeek** [comment]
Chrome automatically supports keyboard shortcuts (but it's kind of hard to find).

Here's a demo video: https://www.youtube.com/watch?v=s3SQVhbmj4c

The Beta release of the extension supports escape-key unzooming

**Comment by sachinsid** [comment]
Thank you! That works like a charm!

**Comment by EmC350** [comment]
Is there a way to get the shortcut to work in a popup window?

I use the extension "Tab to Window/Popup". The problem is once in a popup, the shortcut no longer works to maximize the video.
I noticed the shortcut doesn't give the option to choose between "in chrome" or "global". Maybe that is the key.

**Comment by trophygeek** [comment]
You can try out the Beta version? It has an experimental feature of using the Escape key to try and unzoom. The problem is that the page can intercept these key events, so it isn't 100% reliable.

https://chrome.google.com/webstore/detail/universal-video-maximizer/implccjhhblakjgebfhbafehkjjhklai

**Comment by EmC350** [comment]
The escape key worked in the popup window with the beta to unmaximize, but if I want to re-maximize the video I have to change the popup to a standard window again to use the keyboard shortcut.

Like I mentioned, I noticed that keyboard shortcuts for extensions only work in popup windows when the keyboard shortcut has the option available for "In Chrome" or "Global" in the shortcut settings page. Most likely because the popup window is no longer a standard Chrome window , the shortcut isn't being recognized in the popup without that option being available.

**Comment by trophygeek** [comment]
Yeah. I think you're bumping up against intentional chrome security features to prevent questionable extensions from intercepting command keys? Extensions are kept in a sandbox to limit what they can do/potentially abuse.

But maybe I'm not following exactly what you're doing?

When it fails, is the Video Maximizer speed adjust popup displayed?

**Comment by EmC350** [comment]
It is not displayed because the keyboard shortcut is not being recognized in the popup window at all.

There are other extensions that I use that recognize keyboard shortcuts in popup windows. The "Tab to Window/Popup" extension for example has to recognize keyboard shortcuts in a popup windows for it to be able to change the popup window back to a normal tabbed window using a keyboard shortcut. "Nimbus Screenshot & Screen Video Recorder" also lets me use keyboard shortcuts in a popup window to start recording or take a screenshot of the window. So Chrome security features don't seem to be the cause.

If you open chrome://extensions/shortcuts you will notice that many extensions have the "In Chrome" option to the right greyed out. These keyboard shortcuts from those extensions do not work in a popup window. The extensions that don't have it greyed out and give you the option to choose "In Chrome" or "Global", the keyboard shortcuts do work in popup windows. I don't even have to choose the "Global" option, they just work.
